### ISSUE TITLE
Molecule of the Week Name doesn't show up on iPhone and non-default font size

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#11]
The "Caffeine" label doesn't show up on my iPhone for some reason, so I can't tap it for more information.

**Comment by JoshuaRogan** [comment]
It's an issue with the webgl container not properly clearing. I'm working on a solution. It also happens when the font size is greater then the default

**Comment by JoshuaRogan** [comment]
I put in a workaround that works in most cases. If you make the font really big it will still be hidden on some devices so I am leaving the issue open.

**Comment by JoshuaRogan** [comment]
Fixed with the 3DMol background transparency fix [commit 7f22cf7 ](https://github.com/dkoes/3Dmol.js/commit/7f22cf7c961280f3e9c9f80a3701f5d60e97d3ea)
