### ISSUE TITLE
Automate news articles

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#13]
There should be an automated list of the last X news articles and probably a "news archive" page as well.

Perhaps creating a new news article could be done with a Python script, e.g. "pqr-news-create" or something similar

**Comment by RitwikGupta** [comment]
You could write the news articles in Markdown and then use this `https://github.com/scottstanfield/markdown-to-json` to convert it to JSON, from which we could then put into the page.

**Comment by JoshuaRogan** [comment]
I think we should just build a form with some level of authentication and have that it another mongo collection.

**Comment by RitwikGupta** [comment]
Since the only people updating the news would be Dr. Hutchison or Dr. Lambrecht, I think it would be easier to just to MD to JSON and then run a Python script.

**Comment by ghutchis** [comment]
Can we simply have a directory of Markdown filed ordered by date, eg

2015-05-11-Title.md
2015-05-15-first update.md
2015-06-01-June.md

Etc.

**Comment by JoshuaRogan** [comment]
I'm fine with that. The only problem is if we want to add more features down the road (i.e. comment system, tag system, searching, etc.) it would be better if it was already in a mongo collection and we can just add more pivot tables for additional features as we come up with them. 

But for a simple postings markdown should be fine.

**Comment by ghutchis** [comment]
I think the simple postings would work really well for now.

**Comment by RitwikGupta** [comment]
http://flask.pocoo.org/snippets/19/

**Comment by ghutchis** [comment]
Can we simply create a directory in the backend for the markdown files? If you do it, I'll create the "first launch" document. Filenames will be 2015-06-01-title.md, so it should be easy to parse dates.

**Comment by RitwikGupta** [comment]
I need to create the script for the news page first

**Comment by JoshuaRogan** [comment]
Added article generation. All files in `pqr/static/articles` will be considered news items.
