### ISSUE TITLE
Count of # molecules, # of tags on main page

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#14]
The main page should have some count like "Search by name, InChI, category out of X molecules in Y categories."

This way, as the database grows, people immediately see that the site refreshes.

**Comment by RitwikGupta** [comment]
Maybe even a "Last updated" tag?

**Comment by ghutchis** [comment]
Good idea. Maybe "last updated" goes into the footer.

**Comment by RitwikGupta** [comment]
Fixed with commit cd845e3ea64303c9cf76ae531cdbcae11c690439
