### ISSUE TITLE
Add link to ChemSpider and PubChem pages based on IDs

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#15]
The JSON files give the PubChem ID, and there should be a link on the simple page:

PubChem ID:  <a href="https://pubchem.ncbi.nlm.nih.gov/compound/2244">2244</a>

The detailed list should also give a link to ChemSpider IDs when available:

ChemSpider: <a href="...

I'm creating another issue for links to Wikipedia (which requires more work when generating the JSON).

**Comment by RitwikGupta** [comment]
I want to hold off on the ChemSpider ID for now. We're trying to figure out a way to better check for consistent data, and then we'll add the data that's inconsistent across files.

**Comment by RitwikGupta** [comment]
Added PubChem links with commit 9b46317ddc9f53426a28b6af97b53144f689525a
