### ISSUE TITLE
Add links to Wikipedia pages

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#16]
It's possible to query Wikipedia and get all the InChI keys to create links in the JSON.

Because it's not an ID, the Wikipedia JSON will be an actual URL

**Comment by RitwikGupta** [comment]
How would you go about querying Wikipedia?

**Comment by ghutchis** [comment]
There's an API to execute searches, etc. See, for example:
https://github.com/mwclient/mwclient

I'm downloading articles with chembox, etc. and filtering out the InChIs
