### ISSUE TITLE
Sorting of search results

### ISSUE THREAD

**Issue by dslambrecht** [pittquantum/backend#19]
The search function should return exact matches first and then sort results in decreasing order of relevance. Otherwise the search function will be useless. 

Example: Searching for "ethanol" returns "2,5,8,11,14,17,20,23,26,29,32,35,38,41,44,47,50,53,56,59,62,65,68,71,74,77,80-Heptacosaoxadooctacontan-82-Ol"
as the first result (kind of ridiculous!) and I wasn't even able to locate the ethanol molecule in the 45 pages of search results.

**Comment by JoshuaRogan** [comment]
I agree. Search isn't robust at all right now. It has a long way to go and takes a fair amount of work. We can for sure make some workarounds to make exact matches higher up. But, as far as having a robust relevance system will take a little bit of time.

**Comment by RitwikGupta** [comment]
Ugh yes I agree. Same if you search for `benzene`. I think we should introduce categories as radio buttons to search from, like `name`, or `synonyms`, or `tags`

**Comment by JoshuaRogan** [comment]
I think we should apply what google does. We keep the very simple search box on the home page and navbar. But, once you actually search present some 'search tools' to narrow down your search.

**Comment by RitwikGupta** [comment]
I don't know why my weighting isn't working.
https://github.com/pittquantum/backend/blob/bd2ebb6e22ed58b8433e8baceb5dca27b5ec4de2/scripts/recursive_iterate.py#L92:L98

**Comment by ghutchis** [comment]
@RitwikGupta That's on the Mongo side - I'd check to see if the new weightings are stored for already-created records? I don't know how you're executing the query, but perhaps it'd be easier to sort as the query is executed by Flask?

**Comment by RitwikGupta** [comment]
I'm creating the weightings on the Mongo side, but they're not working for some reason

**Comment by ghutchis** [comment]
We need to revisit this. We can talk about how the search is done (e.g., do you make multiple queries into Mongo for the different fields)?

But we can weight / sort on the server side. My suggestion would be:
- exact match for name field = highest score
- synonym match = lower
- tag match = lower

Inside each search category, sort by the molecular mass or the number of atoms. Usually users typing in "aspirin" want the base compound, which almost always has the lowest molar mass.

**Comment by RitwikGupta** [comment]
Fixed with a stop gap 5e74a9aa7fc84ab930b14c0c8d8e697adf1077e5
