### ISSUE TITLE
WebGL Error Page

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#22]
If the user doesn't have WebGL installed (e.g., old versions of IE, old iOS, etc.) they should be redirected to a page of our choosing.

> I thought you might want to know that the URL you gave us for the Pitt Quantum Repository (http://pqr.pitt.edu/) creates an ugly error in all but the most recent versions of Internet Explorer. It works just fine in Chrome and Firefox, but there are lots of folks still using IE, so you may or may not want to address this.

**Comment by RitwikGupta** [comment]
@JoshuaRogan Are we using Modernizr? If so, it has a WebGL checker built in: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/webgl.js

Otherwise, 
```javascript
if (!window.WebGLRenderingContext) {
    window.location = "http://url.com";
  }
```

**Comment by JoshuaRogan** [comment]
Yes. I can get that up today.

**Comment by JoshuaRogan** [comment]
I currently have the redirect in place to https://get.webgl.org/ We can create a separate page or even a workaround that doesn't require webgl in the future. 

I tested in Firefox successfully but couldn't get webgl to disable in chrome.
