### ISSUE TITLE
Safari WebGl

### ISSUE THREAD

**Issue by JoshuaRogan** [pittquantum/backend#27]
Modernizr not recognizing webGL enabled on mac safari.

**Comment by RitwikGupta** [comment]
I don't have this issue. Safari recognizes WebGL, but the surface looks different than it does on Chrome.

![Surface](http://i.imgur.com/o76Wyg9.png)

Safari 8.0.6, OSX 10.10

**Comment by ghutchis** [comment]
Can this be closed? Starting with Safari 8, WebGL should be enabled by default.
