### ISSUE TITLE
Click / Tap to Stop Spinning?

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#29]
Can we have a click or tap on the molecule to stop spinning? I think once the user starts to move the molecule around themselves, it shouldn't spin anymore.

**Comment by dslambrecht** [comment]
We should turn off rotation by default. I met with the Pittsburgh Public School coordinator and the rotation froze her (ancient) desktop computer.

**Comment by JoshuaRogan** [comment]
I will turn it off by default but I will make it retain the last setting you had. So if you turn it on for any molecule it will be on for all. But, once you shut it off for one it will be off for all. 

I will also make it stop rotating on first touch.
