### ISSUE TITLE
Compressed Transfer

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#36]
All the data is uncompressed:
http://www.webpagetest.org/result/150701_BB_156V/

Compressing the JS and CSS would decrease the size of the first access by ~1 MB, which is meaningful for mobile users.

I'd like to see support for compressed mol2 transfer, if possible, since some of those files can get large.

**Comment by JoshuaRogan** [comment]
Okay, I believe something like this would work: https://flask-compress.readthedocs.org/en/latest/

I will add it tonight.

**Comment by JoshuaRogan** [comment]
Done now with ngnix.

**Comment by ghutchis** [comment]
Can we close this only when it hits production? Thanks.
