### ISSUE TITLE
Set cache/expires headers for static assets

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#37]
This is a big savings for mostly static assets - we could set expires to be ~7 days.

From webpagetest:
An "Expires" header is present (and is not 0 or -1) or a "cache-control: max-age" directive is present and set for an hour or greater.

**Comment by RitwikGupta** [comment]
This is already set, it's just for less than 30 days, that's why the warning is present.

**Comment by ghutchis** [comment]
It's not set for the main page (or any given molecule page). We should set it to 1 day or something like that.

**Comment by JoshuaRogan** [comment]
http://pqr1-prod.chem.pitt.edu/ has the correct config. Will add it to production after a little more testing.
