### ISSUE TITLE
Create API calls

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#38]
There should be some simple, documented REST web API calls that can be integrated into code and a Python module.

e.g.
pqr.pitt.edu/search?name=aspirin

returns a list of InChI keys matching the search

pqr.pitt.edu/api/inchikeys

returns a list of *all* InChI keys, allowing mirroring.

pqr.pitt.edu/mol2/... sends the appropriate mol2 file (i.e., from /static/..)
pqr.pitt.edu/json/... sends the appropriate json file

This can be expanded for future downloads (i.e., the mopac outputs)
pqr.pitt.edu/aux/...
pqr.pitt.edu/mopout/...

**Comment by RitwikGupta** [comment]
pqr.pitt.edu/data/<inchikey> already returns JSON

**Comment by ghutchis** [comment]
Right, but we:
* need more calls, including the ability to write python scripts for searches
* get all inchi keys
* need documentation on the calls..

**Comment by RitwikGupta** [comment]
Done with commit #32e3483

**Comment by RitwikGupta** [comment]
/api/json/{INCHIKEY}
/api/mol2/{INCHIKEY}
/api/inchikeys

**Comment by ghutchis** [comment]
Thanks. Great start. :+1: 

We need to also add some sort of /api/search/ calls, e.g. by name, by tag, etc.
