### ISSUE TITLE
Mainpage "rotation lock" set incorrectly

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#40]
At the moment, the "rotation lock" for the molecule of the week is set incorrectly by default. It looks like rotation should occur, but it doesn't.

<img width="503" alt="screen shot 2015-07-03 at 11 15 07 am" src="https://cloud.githubusercontent.com/assets/41128/8501576/de4f6234-2174-11e5-941b-ad3f5582a003.png">

**Comment by JoshuaRogan** [comment]
Fixed. Not pushed to production yet.
