### ISSUE TITLE
Google Analytics not working?

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#55]
We should have a Google Analytics tag with ID UA-58700553-1
This seems to currently be missing.

**Comment by ghutchis** [comment]
Well, at least according to the Google Anaytics dashboard, which claims the tracking code was not implemented.

**Comment by RitwikGupta** [comment]
I didn't even know we had a tag. @JoshuaRogan

**Comment by JoshuaRogan** [comment]
We shouldn't I was going to ask if we should set it up or if there is some alternative analytic system that Pitt offers.

**Comment by JoshuaRogan** [comment]
I will add it with that code tonight.

**Comment by ghutchis** [comment]
Pitt uses Google analytics, which was on the old "preview" page with the UA code above.
