### ISSUE TITLE
Implement Molecule-of-the-Week Table

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#8]
I can give a set of molecules of the week (i.e., week X, use key XXX-XX-X). What should the format of the file look like?

**Comment by JoshuaRogan** [comment]
I'd say just make a JSON file with an array of dates(YYYY-MM-DD) and keys. That would be the most flexible way.

**Comment by JoshuaRogan** [comment]
Or just an array of keys and we can manage the timing

**Comment by RitwikGupta** [comment]
I would like for the file to be a CSV file.
```
integer_date,key
integer_date,key
...
```
This way, on server start, we can load everything into memory into a dictionary and just do a quick O(1) lookup for the MotW

**Comment by RitwikGupta** [comment]
See https://github.com/pittquantum/backend/blob/master/pqr/redirects/redirect_file for what I mean

**Comment by RitwikGupta** [comment]
See https://github.com/pittquantum/backend/blob/master/pqr/redirects/redirect_file and https://github.com/pittquantum/backend/blob/master/pqr/views.py#L206 for what I mean

**Comment by RitwikGupta** [comment]
Integer date should be YYYYMMDD

**Comment by RitwikGupta** [comment]
Solved with commit 5b282b967525ae792dd4d4cce555b0dae5180a20
