### ISSUE TITLE
"Pitt Quantum Repository" in heading wraps poorly on iPhone

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/backend#9]
On the phone, "Pitt Quantum Repository" in the heading bar should either be shortened (via JavaScript) to PQR or the font size should drop vs. desktop. Right now, there's an ugly wrap into a second line below the pseudo molecule logo

**Comment by JoshuaRogan** [comment]
I fixed this but in the future we will also have the links to our other pages on the top so we might always default to PQR.
